# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'abbealexpenses' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for abbealexpenses
  pod 'GoogleSignIn'

  # target 'abbealexpenses-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'abbealexpensesTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'abbealexpenses-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for abbealexpenses-tvOS

  target 'abbealexpenses-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
