export default {
  FETCH_EXPENSES: 'FETCH_EXPENSES',
  FETCH_EXPENSES_SUCCESS: 'FETCH_EXPENSES_SUCCESS',
  FETCH_EXPENSES_ERROR: 'FETCH_EXPENSES_ERROR',
  UPLOAD_FILE: 'UPLOAD_FILE',
  UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
  UPLOAD_FILE_ERROR: 'UPLOAD_FILE_ERROR',
  NEW_PICTURE: 'NEW_PICTURE',
  SET_PICTURE_BASE64: 'SET_PICTURE_BASE64',
  DISMISS_PICTURE: 'DISMISS_PICTURE',
  CONFIRM_PICTURE: 'CONFIRM_PICTURE',
};
