export default {
  FETCH_EXPENSES: 'FETCH_EXPENSES',
  FETCH_EXPENSES_SUCCESS: 'FETCH_EXPENSES_SUCCESS',
  FETCH_EXPENSES_ERROR: 'FETCH_EXPENSES_ERROR',
  UPLOAD_FILE: 'UPLOAD_FILE',
  UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
  UPLOAD_FILE_ERROR: 'UPLOAD_FILE_ERROR',
};
